swagger: '2.0'
info:
  version: 0.0.1
  title: Savings Cost Predictor
host: scp.url
basePath: /
tags:
  - name: Healthcheck
    description: Status of service
  - name: Savings
    description: For existing customers, accessed by front-end console
  - name: Onboarding
    description: For new customers
  - name: AWS Only
    description: Will be accessed only by AWS through SNS
paths:
  "/aws/healthcheck":
    get:
      tags:
        - healthcheck
      summary: "Returns service status"
      description: "Checks if our APIs are online and AWS is online"
      operationId: getStatus
      produces:
        - application/json
      responses:
        '200':
          description: All services online
  "/aws/account/register":
    post:
      tags:
        - Onboarding
      summary: "Registers user and emails report"
      description: ""
      operationId: awsRegister
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: userData
          in: body          
          description: "JSON object containing the user information"
          required: true
          schema:
            $ref: '#/definitions/UserData'
      responses:
        '200':
          description: "Details saved"
  "/aws/account/new":
    get:
      tags:
        - Onboarding
      summary: "Get UUID and CF template link"
      description: "Creates a CF template "
      operationId: awsNew
      produces:
        - application/json
      responses:
        '200':
          description: "Generated Data"
          schema:
            $ref: '#/definitions/GeneratedData'
  "/aws/account/{UUID}":
    get:
      tags:
        - Onboarding
      summary : ""
      description: ""
      operationId: ""
      produces:
        - application/json
      parameters:
        - name: UUID
          in: path
          type: string
          required: true
          description: "UUID of the UUID:RoleARN mapping"
      responses:
        '200':
          description: "The RoleARN of the corresponding" 
          schema:
            $ref: '#/definitions/RoleArnData'
        '404':
          description: "The RoleARN has not yet been delivered by SNS"
  "/savings/aws/{service}/{roleARN}":
    get:
      tags:
        - Savings
      summary: "Savings for a particular service"
      description: "This"
      operationId: ""
      parameters:
        - in: path
          name: service
          type: string
          required: true
          description: "The service whose savings is to be calculated"
          enum: [
                "summary",
                "ec2",
                "asg",
                "emr",
                "ecs",
                "ops"
            ]
        - in: path
          name: roleARN
          type: string
          required: true
          description: "RoleARN of the customer for whom savings is to be calculated"
      produces:
        - application/json
      responses:
        '200':
          description: "An array of savings object"
          schema:
            type: array
            items:
              $ref: '#/definitions/SavingsData'
  "/aws/webhook":
    post:
      tags:
        - AWS Only
      summary: "Endpoint where SNS sends messages "
      description: "This endpoint is to be accessed only by AWS. There will be two type of requests: Subsription confirmation and actual messages."
      operationId: awsWebhook
      consumes:
        - application/json
      responses:
        '200':
          description: "Amazon does not require a response"
          
definitions:
  GeneratedData:
    type: object
    properties:
      UUID:
        type: string
        example: "070a62a7-3000-4eb3-88cb-6f7507695364"
        description: "A version 4 UUID.Assigned to every new user.Used to map email/name to roleARN"
      templateLink:
        type: string
        example: "https://s3.amazonaws.com/scp-test/test-cf-070a62a7-3000-4eb3-88cb-6f7507695364.template"
  RoleArnData:
    type: object
    properties:
      RoleARN:
        type: string
        example: "arn:aws:iam:9999999:role/batchly/batchly-trusted"
        description: "RoleARN generated by AWS for us to access AWS info for a particular customer"
  UserData:
    type: object
    properties:
      username:
        type: string
        example: "John Doe"
      email:
        type: string
        example: "abc@xyz.com"
      RoleARN:
        type: string
        example: "arn:aws:iam:9999999:role/batchly/batchly-trusted"
        description: "RoleARN generated by AWS for us to access AWS info for a particular customer"
      UUID:
        type: string
        example: "070a62a7-3000-4eb3-88cb-6f7507695364"
        description: "A version 4 UUID.Assigned to every new user.Used to map email/name to roleARN"
  SavingsData:
    type: object
    properties:
      serviceType:
        type: string
        enum: ["ec2","emr","ecs","ops","asg"]
      savings:
        type: number
        format: double
      count:
        type: integer
